#!/bin/bash

# Copyright (C) 2025 Nicolás Ortega Froysa <nicolas@ortegas.org> All rights reserved.
# Author: Nicolás Ortega Froysa <nicolas@ortegas.org>
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
#
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
#
# 3. This notice may not be removed or altered from any source
#    distribution.

YT_URL="$1"
INVID_BASE="${INVID_BASE:-https://inv.nadeko.net}"

if [ $# -ne 1 ]
then
	>&2 echo "Usage: $0 <url>"
	exit 1
elif [ "$1" = "-h" ]
then
	echo "Usage: $0 <url>"
	exit 0
fi

if [[ $YT_URL == *"youtu.be"* ]]
then
	INVID_URL="${INVID_BASE}/watch?v=${YT_URL##*/}"
elif [[ $YT_URL == *"www.youtube.com"* ]]
then
	INVID_URL="${INVID_BASE}/${YT_URL##*/}"
fi

echo "$INVID_URL"
