#!/bin/bash

set -euo pipefail

[ "$#" -eq 0 ] &&
	echo "Requires a command. Run with 'help' for a list of commands." &&
	exit 1

case $1 in
	"wallet")
		monero-wallet-cli --daemon-address node.monero.net:13666
		;;
	"address")
		echo "42espNaUqPdJK4vTir4NDfH4gT6brFR4F5KPRADrg5t98LkzHnQfFnUDZZEetp3Zw5K8V4v364tN3TMxfg4eXEN9RpnrNBG"
		;;
	"help")
		echo "USAGE: monero-client [command]
Commands:
	address   print out the monero public address
	mine      start the miner
	wallet    open the monero wallet
	help      show this help information"
		;;
	*)
		echo "Invalid command '$1'. Please run with the 'help' option."
		;;
esac
