#!/bin/bash

set -euo pipefail

if [ $# -gt 1 ]
then
	echo "Too many arguments"
	exit 1
elif [ $# -eq 1 ]
then
	cp $1 $HOME/.local/share/wallpaper.jpg
fi

xwallpaper --zoom $HOME/.local/share/wallpaper.jpg
